// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC264jFlIysr5FPfJK8H_IahvJwtaQ1Ig',
    appId: '1:20251967698:web:2a316a0a62800ca125ed0b',
    messagingSenderId: '20251967698',
    projectId: 'shopngo-app',
    authDomain: 'shopngo-app.firebaseapp.com',
    storageBucket: 'shopngo-app.firebasestorage.app',
    measurementId: 'G-HK34GHCEV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5jEBTbLeedcoE19E9m-fcLf6rjs7O9b8',
    appId: '1:20251967698:android:63b4db60c843dc4625ed0b',
    messagingSenderId: '20251967698',
    projectId: 'shopngo-app',
    storageBucket: 'shopngo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8uJ9JfVETb5yMmHKYYBFSnwQS2Qzrncs',
    appId: '1:20251967698:ios:94c3b3a53f86873025ed0b',
    messagingSenderId: '20251967698',
    projectId: 'shopngo-app',
    storageBucket: 'shopngo-app.firebasestorage.app',
    iosBundleId: 'com.example.shopngo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8uJ9JfVETb5yMmHKYYBFSnwQS2Qzrncs',
    appId: '1:20251967698:ios:94c3b3a53f86873025ed0b',
    messagingSenderId: '20251967698',
    projectId: 'shopngo-app',
    storageBucket: 'shopngo-app.firebasestorage.app',
    iosBundleId: 'com.example.shopngo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC264jFlIysr5FPfJK8H_IahvJwtaQ1Ig',
    appId: '1:20251967698:web:831f3ff1ad98eb7c25ed0b',
    messagingSenderId: '20251967698',
    projectId: 'shopngo-app',
    authDomain: 'shopngo-app.firebaseapp.com',
    storageBucket: 'shopngo-app.firebasestorage.app',
    measurementId: 'G-01TL6QKR2Y',
  );
}
